// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

type State struct {
	Lock             interface{} `json:"lock"`
	CurrentPageToken string      `json:"current_page_token"`
}
