// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

type File struct {
	ID          int64       `json:"id"`
	Path        string      `json:"path"`
	ContentHash interface{} `json:"content_hash"`
}
