// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

type Config struct {
	ID           int64  `json:"id"`
	RootDir      string `json:"root_dir"`
	SyncInterval int64  `json:"sync_interval"`
}

type File struct {
	Path         string `json:"path"`
	DriveID      string `json:"drive_id"`
	ContentHash  []byte `json:"content_hash"`
	LastModified int64  `json:"last_modified"`
}

type State struct {
	ID               int64  `json:"id"`
	CurrentPageToken string `json:"current_page_token"`
}
