// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"
)

const deleteFile = `-- name: DeleteFile :exec
DELETE
FROM files
WHERE path = ?
`

func (q *Queries) DeleteFile(ctx context.Context, path string) error {
	_, err := q.db.ExecContext(ctx, deleteFile, path)
	return err
}

const getAllFiles = `-- name: GetAllFiles :many
SELECT path, drive_id, content_hash, last_modified
FROM files
ORDER BY path
`

func (q *Queries) GetAllFiles(ctx context.Context) ([]File, error) {
	rows, err := q.db.QueryContext(ctx, getAllFiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.Path,
			&i.DriveID,
			&i.ContentHash,
			&i.LastModified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuthToken = `-- name: GetAuthToken :one
SELECT auth_token
FROM state
WHERE id = 1
`

func (q *Queries) GetAuthToken(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getAuthToken)
	var auth_token string
	err := row.Scan(&auth_token)
	return auth_token, err
}

const getConfig = `-- name: GetConfig :one
SELECT id, root_dir, sync_interval
FROM config
WHERE id = 1
`

func (q *Queries) GetConfig(ctx context.Context) (Config, error) {
	row := q.db.QueryRowContext(ctx, getConfig)
	var i Config
	err := row.Scan(&i.ID, &i.RootDir, &i.SyncInterval)
	return i, err
}

const getFile = `-- name: GetFile :one
SELECT path, drive_id, content_hash, last_modified
FROM files
WHERE path = ?
`

func (q *Queries) GetFile(ctx context.Context, path string) (File, error) {
	row := q.db.QueryRowContext(ctx, getFile, path)
	var i File
	err := row.Scan(
		&i.Path,
		&i.DriveID,
		&i.ContentHash,
		&i.LastModified,
	)
	return i, err
}

const getPageToken = `-- name: GetPageToken :one
SELECT page_token
FROM state
WHERE id = 1
`

func (q *Queries) GetPageToken(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getPageToken)
	var page_token string
	err := row.Scan(&page_token)
	return page_token, err
}

const isInitialized = `-- name: IsInitialized :one
SELECT is_initialized
FROM state
WHERE id = 1
`

func (q *Queries) IsInitialized(ctx context.Context) (bool, error) {
	row := q.db.QueryRowContext(ctx, isInitialized)
	var is_initialized bool
	err := row.Scan(&is_initialized)
	return is_initialized, err
}

const setInitialized = `-- name: SetInitialized :exec
UPDATE state
SET is_initialized = true
`

func (q *Queries) SetInitialized(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, setInitialized)
	return err
}

const updateAuthToken = `-- name: UpdateAuthToken :exec
UPDATE state
SET auth_token = ?
WHERE id = 1
`

func (q *Queries) UpdateAuthToken(ctx context.Context, authToken string) error {
	_, err := q.db.ExecContext(ctx, updateAuthToken, authToken)
	return err
}

const updatePageToken = `-- name: UpdatePageToken :exec
UPDATE state
SET page_token = ?
WHERE id = 1
`

func (q *Queries) UpdatePageToken(ctx context.Context, pageToken string) error {
	_, err := q.db.ExecContext(ctx, updatePageToken, pageToken)
	return err
}

const upsertConfig = `-- name: UpsertConfig :exec
INSERT INTO config (root_dir, sync_interval)
VALUES (?, ?)
ON CONFLICT (id) DO UPDATE SET root_dir      = EXCLUDED.root_dir,
                               sync_interval = EXCLUDED.sync_interval
`

type UpsertConfigParams struct {
	RootDir      string `json:"root_dir"`
	SyncInterval int64  `json:"sync_interval"`
}

func (q *Queries) UpsertConfig(ctx context.Context, arg UpsertConfigParams) error {
	_, err := q.db.ExecContext(ctx, upsertConfig, arg.RootDir, arg.SyncInterval)
	return err
}

const upsertFile = `-- name: UpsertFile :exec
INSERT INTO files (path, drive_id, content_hash, last_modified)
VALUES (?, ?, ?, ?)
ON CONFLICT (path)
    DO UPDATE SET content_hash  = EXCLUDED.content_hash,
                  last_modified = EXCLUDED.last_modified
`

type UpsertFileParams struct {
	Path         string `json:"path"`
	DriveID      string `json:"drive_id"`
	ContentHash  []byte `json:"content_hash"`
	LastModified int64  `json:"last_modified"`
}

func (q *Queries) UpsertFile(ctx context.Context, arg UpsertFileParams) error {
	_, err := q.db.ExecContext(ctx, upsertFile,
		arg.Path,
		arg.DriveID,
		arg.ContentHash,
		arg.LastModified,
	)
	return err
}
