// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package sqlc

import (
	"context"
)

const getConfig = `-- name: GetConfig :one
SELECT lock, current_page_token FROM state
`

func (q *Queries) GetConfig(ctx context.Context) (State, error) {
	row := q.db.QueryRowContext(ctx, getConfig)
	var i State
	err := row.Scan(&i.Lock, &i.CurrentPageToken)
	return i, err
}
